/**
 * BookManager — CRUD for the free library, including the table of contents.
 *
 * Cover art and the download URL are generated by the API when left blank, so
 * the owner only has to type a title and a description to publish a book.
 */

import { useState, type FormEvent } from 'react';
import { ApiError } from '../../api/client';
import { adminApi } from '../../api/endpoints';
import { useToast } from '../../context/ToastContext';
import { useApi } from '../../hooks/useApi';
import { formatDate, pluralise } from '../../lib/format';
import { validateRequired, validateSlug, validateUrl } from '../../lib/validation';
import type { Book, TocEntry } from '../../types';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';
import { CheckboxField, TextAreaField, TextField } from '../ui/Field';
import { ConfirmDialog, Modal } from '../ui/Modal';
import { ErrorState } from '../ui/States';
import { DataTable, type Column } from './DataTable';

interface BookFormState {
  title: string;
  slug: string;
  subtitle: string;
  author: string;
  category: string;
  language: string;
  pages: string;
  edition: string;
  published_on: string;
  description: string;
  tags: string;
  cover_url: string;
  file_url: string;
  is_free: boolean;
  is_published: boolean;
  is_featured: boolean;
  sort_order: string;
  toc: TocEntry[];
}

const EMPTY_BOOK: BookFormState = {
  title: '',
  slug: '',
  subtitle: '',
  author: 'Rehan Rae Essayyed',
  category: 'Religion',
  language: 'English',
  pages: '',
  edition: 'First edition',
  published_on: '',
  description: '',
  tags: '',
  cover_url: '',
  file_url: '',
  is_free: true,
  is_published: true,
  is_featured: false,
  sort_order: '0',
  toc: [],
};

export function BookManager(): JSX.Element {
  const { success, error: notifyError } = useToast();
  const { data: books, loading, error, reload } = useApi<Book[]>(() => adminApi.books(), []);

  const [editing, setEditing] = useState<{ mode: 'create' | 'edit'; book: Book | null } | null>(null);
  const [form, setForm] = useState<BookFormState>(EMPTY_BOOK);
  const [errors, setErrors] = useState<Record<string, string | undefined>>({});
  const [saving, setSaving] = useState(false);
  const [pendingDelete, setPendingDelete] = useState<Book | null>(null);

  function openCreate(): void {
    setForm({ ...EMPTY_BOOK, sort_order: String((books?.length ?? 0) + 1) });
    setErrors({});
    setEditing({ mode: 'create', book: null });
  }

  function openEdit(book: Book): void {
    setForm({
      title: book.title,
      slug: book.slug,
      subtitle: book.subtitle ?? '',
      author: book.author,
      category: book.category ?? '',
      language: book.language,
      pages: book.pages ? String(book.pages) : '',
      edition: book.edition ?? '',
      published_on: book.published_on ?? '',
      description: book.description,
      tags: book.tags.join(', '),
      cover_url: book.cover_url ?? '',
      file_url: book.file_url ?? '',
      is_free: book.is_free,
      is_published: book.is_published,
      is_featured: book.is_featured,
      sort_order: String(book.sort_order),
      toc: book.table_of_contents ?? [],
    });
    setErrors({});
    setEditing({ mode: 'edit', book });
  }

  function updateToc(index: number, patch: Partial<TocEntry>): void {
    setForm((current) => ({
      ...current,
      toc: current.toc.map((entry, position) => (position === index ? { ...entry, ...patch } : entry)),
    }));
  }

  async function submit(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    const nextErrors: Record<string, string | undefined> = {
      title: validateRequired('Title')(form.title) ?? undefined,
      slug: validateSlug(form.slug) ?? undefined,
      cover_url: validateUrl(form.cover_url) ?? undefined,
      file_url: validateUrl(form.file_url) ?? undefined,
    };
    setErrors(nextErrors);
    if (Object.values(nextErrors).some(Boolean)) return;

    const payload = {
      title: form.title.trim(),
      slug: form.slug.trim() || undefined,
      subtitle: form.subtitle || null,
      author: form.author || 'Rehan Rae Essayyed',
      category: form.category || null,
      language: form.language || 'English',
      pages: form.pages ? Number(form.pages) : null,
      edition: form.edition || null,
      published_on: form.published_on || null,
      description: form.description,
      tags: form.tags
        .split(',')
        .map((tag) => tag.trim())
        .filter(Boolean),
      cover_url: form.cover_url || null,
      file_url: form.file_url || null,
      is_free: form.is_free,
      is_published: form.is_published,
      is_featured: form.is_featured,
      sort_order: Number(form.sort_order) || 0,
      table_of_contents: form.toc.filter((entry) => entry.title.trim()),
    };

    setSaving(true);
    try {
      if (editing?.mode === 'edit' && editing.book) {
        await adminApi.updateBook(editing.book.id, payload);
        success('Book updated', payload.title);
      } else {
        await adminApi.createBook(payload);
        success('Book published', `${payload.title} is live in the library.`);
      }
      setEditing(null);
      reload();
    } catch (caught) {
      notifyError('Could not save book', caught instanceof ApiError ? caught.message : 'Try again.');
    } finally {
      setSaving(false);
    }
  }

  async function remove(): Promise<void> {
    if (!pendingDelete) return;
    setSaving(true);
    try {
      await adminApi.deleteBook(pendingDelete.id);
      success('Book deleted', pendingDelete.title);
      setPendingDelete(null);
      reload();
    } catch (caught) {
      notifyError('Could not delete book', caught instanceof ApiError ? caught.message : 'Try again.');
    } finally {
      setSaving(false);
    }
  }

  const columns: Column<Book>[] = [
    {
      key: 'book',
      header: 'Book',
      render: (row) => (
        <div className="cell-person">
          <strong>{row.title}</strong>
          <span>{row.subtitle ?? `/books/${row.slug}`}</span>
        </div>
      ),
    },
    { key: 'category', header: 'Category', render: (row) => <Badge tone="latte">{row.category ?? '—'}</Badge> },
    { key: 'pages', header: 'Pages', align: 'right', render: (row) => <span className="cell-numbers">{row.pages ?? '—'}</span> },
    { key: 'downloads', header: 'Downloads', align: 'right', render: (row) => <span className="cell-numbers">{row.download_count}</span> },
    {
      key: 'published_on',
      header: 'Published',
      render: (row) => <span className="cell-muted">{row.published_on ? formatDate(row.published_on) : '—'}</span>,
    },
    {
      key: 'status',
      header: 'Status',
      render: (row) => (
        <Badge tone={row.is_published ? 'success' : 'muted'}>{row.is_published ? 'Live' : 'Draft'}</Badge>
      ),
    },
    {
      key: 'actions',
      header: 'Actions',
      align: 'right',
      render: (row) => (
        <div className="cell-actions">
          <Button size="sm" variant="ghost" onClick={() => openEdit(row)}>
            Edit
          </Button>
          <Button size="sm" variant="danger" onClick={() => setPendingDelete(row)}>
            Delete
          </Button>
        </div>
      ),
    },
  ];

  if (error) return <ErrorState message={error} onRetry={reload} />;

  return (
    <section className="manager" aria-labelledby="books-admin-title">
      <header className="manager__head">
        <div>
          <h2 className="manager__title" id="books-admin-title">
            Books
          </h2>
          <p className="manager__subtitle">
            {pluralise(books?.length ?? 0, 'book')} ·{' '}
            {pluralise((books ?? []).reduce((total, book) => total + book.download_count, 0), 'download')}
          </p>
        </div>
        <div className="manager__actions">
          <Button size="sm" onClick={openCreate}>
            + New book
          </Button>
          <Button size="sm" variant="ghost" onClick={reload}>
            Refresh
          </Button>
        </div>
      </header>

      <DataTable
        rows={books ?? []}
        columns={columns}
        rowKey={(row) => row.id}
        caption="Books in the library"
        loading={loading}
        emptyMessage="No books yet — publish your first one."
      />

      <Modal
        open={editing !== null}
        title={editing?.mode === 'edit' ? `Edit “${editing.book?.title ?? ''}”` : 'New book'}
        description="Leave the cover and file URL empty to let the server generate artwork and a PDF download."
        onClose={() => setEditing(null)}
        size="lg"
        footer={
          <>
            <Button variant="secondary" onClick={() => setEditing(null)} disabled={saving}>
              Cancel
            </Button>
            <Button form="book-form" type="submit" loading={saving}>
              {editing?.mode === 'edit' ? 'Save changes' : 'Publish book'}
            </Button>
          </>
        }
      >
        <form id="book-form" className="form-grid form-grid--2" onSubmit={submit} noValidate>
          <TextField
            label="Title"
            id="book-form-title"
            required
            value={form.title}
            error={errors.title}
            onChange={(event) => setForm({ ...form, title: event.target.value })}
          />
          <TextField
            label="Slug"
            id="book-form-slug"
            placeholder="auto-generated when blank"
            value={form.slug}
            error={errors.slug}
            onChange={(event) => setForm({ ...form, slug: event.target.value })}
          />
          <TextField
            label="Subtitle"
            id="book-form-subtitle"
            value={form.subtitle}
            onChange={(event) => setForm({ ...form, subtitle: event.target.value })}
          />
          <TextField
            label="Author"
            id="book-form-author"
            value={form.author}
            onChange={(event) => setForm({ ...form, author: event.target.value })}
          />
          <TextField
            label="Category"
            id="book-form-category"
            value={form.category}
            onChange={(event) => setForm({ ...form, category: event.target.value })}
          />
          <TextField
            label="Language"
            id="book-form-language"
            value={form.language}
            onChange={(event) => setForm({ ...form, language: event.target.value })}
          />
          <TextField
            label="Pages"
            id="book-form-pages"
            type="number"
            min={1}
            value={form.pages}
            onChange={(event) => setForm({ ...form, pages: event.target.value })}
          />
          <TextField
            label="Edition"
            id="book-form-edition"
            value={form.edition}
            onChange={(event) => setForm({ ...form, edition: event.target.value })}
          />
          <TextField
            label="Published on"
            id="book-form-date"
            type="date"
            value={form.published_on}
            onChange={(event) => setForm({ ...form, published_on: event.target.value })}
          />
          <TextField
            label="Sort order"
            id="book-form-order"
            type="number"
            value={form.sort_order}
            onChange={(event) => setForm({ ...form, sort_order: event.target.value })}
          />
          <TextField
            label="Tags"
            id="book-form-tags"
            placeholder="comma, separated, list"
            value={form.tags}
            onChange={(event) => setForm({ ...form, tags: event.target.value })}
          />
          <TextField
            label="Cover URL"
            id="book-form-cover"
            value={form.cover_url}
            error={errors.cover_url}
            hint="Blank = generated artwork"
            onChange={(event) => setForm({ ...form, cover_url: event.target.value })}
          />
          <TextField
            label="File URL"
            id="book-form-file"
            value={form.file_url}
            error={errors.file_url}
            hint="Blank = generated PDF download"
            onChange={(event) => setForm({ ...form, file_url: event.target.value })}
          />

          <div className="form-grid__span">
            <TextAreaField
              label="Description"
              id="book-form-description"
              rows={6}
              hint="Markdown supported: blank line = new paragraph, ## = heading."
              value={form.description}
              onChange={(event) => setForm({ ...form, description: event.target.value })}
            />
          </div>

          <div className="form-grid__span checkbox-row">
            <CheckboxField
              label="Free"
              checked={form.is_free}
              onChange={(event) => setForm({ ...form, is_free: event.target.checked })}
            />
            <CheckboxField
              label="Published"
              checked={form.is_published}
              onChange={(event) => setForm({ ...form, is_published: event.target.checked })}
            />
            <CheckboxField
              label="Featured on the home shelf"
              checked={form.is_featured}
              onChange={(event) => setForm({ ...form, is_featured: event.target.checked })}
            />
          </div>

          {/* -------------------------------------------------- contents editor */}
          <div className="form-grid__span">
            <div className="sub-editor">
              <div className="sub-editor__head">
                <h3>Table of contents</h3>
                <Button
                  type="button"
                  size="sm"
                  variant="secondary"
                  onClick={() =>
                    setForm({
                      ...form,
                      toc: [
                        ...form.toc,
                        { chapter: String(form.toc.length + 1).padStart(2, '0'), title: '', pages: '' },
                      ],
                    })
                  }
                >
                  + Add chapter
                </Button>
              </div>

              {form.toc.length === 0 ? (
                <p className="panel__muted">No chapters yet.</p>
              ) : (
                <ul className="sub-editor__list">
                  {form.toc.map((entry, index) => (
                    // eslint-disable-next-line react/no-array-index-key
                    <li key={index} className="sub-editor__row">
                      <input
                        className="input input--sm"
                        aria-label={`Chapter number ${index + 1}`}
                        value={entry.chapter}
                        onChange={(event) => updateToc(index, { chapter: event.target.value })}
                      />
                      <input
                        className="input input--sm"
                        aria-label={`Chapter title ${index + 1}`}
                        placeholder="Chapter title"
                        value={entry.title}
                        onChange={(event) => updateToc(index, { title: event.target.value })}
                      />
                      <input
                        className="input input--sm"
                        aria-label={`Pages ${index + 1}`}
                        placeholder="1—12"
                        value={entry.pages ?? ''}
                        onChange={(event) => updateToc(index, { pages: event.target.value })}
                      />
                      <Button
                        type="button"
                        size="sm"
                        variant="ghost"
                        aria-label={`Remove chapter ${index + 1}`}
                        onClick={() =>
                          setForm({ ...form, toc: form.toc.filter((_, position) => position !== index) })
                        }
                      >
                        ✕
                      </Button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </form>
      </Modal>

      <ConfirmDialog
        open={pendingDelete !== null}
        title={`Delete “${pendingDelete?.title ?? ''}”?`}
        message="The book and its download link will be removed from the library."
        confirmLabel="Delete book"
        busy={saving}
        onConfirm={() => void remove()}
        onCancel={() => setPendingDelete(null)}
      />
    </section>
  );
}
